package com.goeo1066.sample.java_code_creator_sample;

// the class generated by Open AI
public class Calculator {
    private int result;

    public void clear() {
        // Clears the calculator result
        this.result = 0;
    }

    public int getResult() {
        // Returns the current result stored in the calculator
        return this.result;
    }

    public void add(int operand) {
        // Adds the given operand to the calculator result
        this.result += operand;
    }

    public void subtract(int operand) {
        // Subtracts the given operand from the calculator result
        this.result -= operand;
    }

    public void multiply(int operand) {
        // Multiplies the calculator result by the given operand
        this.result *= operand;
    }

    public void divide(int operand) {
        // Divides the calculator result by the given operand
        this.result /= operand;
    }
}

/**
 * A domain entity representing a calculator.
 */